[env:sunton-s3-43]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; --- MEMORY ---
board_build.arduino.memory_type = qio_opi
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB

; --- BUILD FLAGS ---
build_flags = 
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -D LV_CONF_INCLUDE_SIMPLE  ; Important: tells LVGL to look for lv_conf.h simply
    -D LV_COMP_CONF_INCLUDE_SIMPLE
    -I src                     ; Tells compiler to look in src/ folder for lv_conf.h

; --- LIBRARIES ---
lib_deps =
    https://github.com/moononournation/Arduino_GFX.git#v1.4.7
    https://github.com/tzapu/WiFiManager.git
    https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
    lvgl/lvgl @ ^8.3.11        ; Install LVGL v8