[env:sunton-s3-43]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; --- MEMORY SETTINGS ---
board_build.arduino.memory_type = qio_opi
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_upload.flash_size = 16MB

; !!! CHANGED THIS LINE !!!
board_build.partitions = partitions.csv 

; --- BUILD FLAGS ---
build_flags = 
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -D LV_CONF_INCLUDE_SIMPLE
    -D LV_COMP_CONF_INCLUDE_SIMPLE
    -I src
    -I src/ui

; --- LIBRARIES ---
lib_deps =
    https://github.com/moononournation/Arduino_GFX.git#v1.4.7
    https://github.com/tzapu/WiFiManager.git
    https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
    lvgl/lvgl @ ^8.3.11

monitor_speed = 115200