// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_Label3;
lv_obj_t * uic_Label1;
lv_obj_t * uic_Panel4;
lv_obj_t * uic_Chart1;
lv_obj_t * uic_Image3;
lv_obj_t * uic_Roller1;
lv_obj_t * ui_home_screen = NULL;
lv_obj_t * ui_Roller1 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Chart1 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_Panel6 = NULL;
lv_obj_t * ui_Panel7 = NULL;
lv_obj_t * ui_Panel9 = NULL;
lv_obj_t * ui_Panel8 = NULL;
lv_obj_t * ui_Panel10 = NULL;
// event funtions

// build funtions

void ui_home_screen_screen_init(void)
{
    ui_home_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_home_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_home_screen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_home_screen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);

    ui_Roller1 = lv_roller_create(ui_home_screen);
    lv_roller_set_options(ui_Roller1, "Overview\nZone 1\nZone 2\nSettings", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_Roller1, 99);
    lv_obj_set_width(ui_Roller1, LV_SIZE_CONTENT);   /// 4
    lv_obj_set_x(ui_Roller1, 170);
    lv_obj_set_y(ui_Roller1, 75);
    lv_obj_set_align(ui_Roller1, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_Roller1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_button);
    ui_object_set_themeable_style_property(ui_Roller1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_button);
    ui_object_set_themeable_style_property(ui_Roller1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_secondary);
    ui_object_set_themeable_style_property(ui_Roller1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_secondary);
    ui_object_set_themeable_style_property(ui_Roller1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_button2);
    ui_object_set_themeable_style_property(ui_Roller1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_button2);
    lv_obj_set_style_bg_color(ui_Roller1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Roller1, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_object_set_themeable_style_property(ui_Roller1, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_Roller1, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_Roller1, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_button);
    ui_object_set_themeable_style_property(ui_Roller1, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_button);

    ui_Image3 = lv_img_create(ui_home_screen);
    lv_img_set_src(ui_Image3, &ui_img_batt_100_png);
    lv_obj_set_width(ui_Image3, lv_pct(100));
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, 202);
    lv_obj_set_y(ui_Image3, -113);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image3, 30);

    ui_Chart1 = lv_chart_create(ui_home_screen);
    lv_obj_set_width(ui_Chart1, 250);
    lv_obj_set_height(ui_Chart1, 100);
    lv_obj_set_x(ui_Chart1, -70);
    lv_obj_set_y(ui_Chart1, -69);
    lv_obj_set_align(ui_Chart1, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart1, LV_CHART_TYPE_LINE);
    lv_chart_set_range(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 0, 8000);
    lv_chart_set_div_line_count(ui_Chart1, 5, 5);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 4, 0, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 4, 5, 5, 2, true, 25);
    lv_chart_series_t * ui_Chart1_series_1 = lv_chart_add_series(ui_Chart1, lv_color_hex(0x006E44),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart1_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 90 };
    lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_1, ui_Chart1_series_1_array);
    lv_chart_series_t * ui_Chart1_series_2 = lv_chart_add_series(ui_Chart1, lv_color_hex(0x035EBE),
                                                                 LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_Chart1_series_2_array[] = { 0, 20, 40, 80, 60, 40, 20, 80, 90, 150 };
    lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_2, ui_Chart1_series_2_array);
    lv_chart_series_t * ui_Chart1_series_3 = lv_chart_add_series(ui_Chart1, lv_color_hex(0xC01515),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart1_series_3_array[] = { 50, 30, 20, 10, 0, 10, 20, 30, 40, 60 };
    lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_3, ui_Chart1_series_3_array);
    ui_object_set_themeable_style_property(ui_Chart1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_Chart1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_Chart1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_button2);
    ui_object_set_themeable_style_property(ui_Chart1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_button2);
    ui_object_set_themeable_style_property(ui_Chart1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_LINE_COLOR,
                                           _ui_theme_color_secondary);
    ui_object_set_themeable_style_property(ui_Chart1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_LINE_OPA,
                                           _ui_theme_alpha_secondary);
    lv_obj_set_style_pad_left(ui_Chart1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Chart1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Chart1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Chart1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_Chart1, LV_PART_TICKS | LV_STATE_DEFAULT, LV_STYLE_LINE_COLOR,
                                           _ui_theme_color_button2);
    ui_object_set_themeable_style_property(ui_Chart1, LV_PART_TICKS | LV_STATE_DEFAULT, LV_STYLE_LINE_OPA,
                                           _ui_theme_alpha_button2);
    lv_obj_set_style_line_rounded(ui_Chart1, true, LV_PART_TICKS | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Chart1, LV_PART_TICKS | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_button2);
    ui_object_set_themeable_style_property(ui_Chart1, LV_PART_TICKS | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_button2);

    ui_Panel4 = lv_obj_create(ui_home_screen);
    lv_obj_set_width(ui_Panel4, 120);
    lv_obj_set_height(ui_Panel4, 68);
    lv_obj_set_x(ui_Panel4, 171);
    lv_obj_set_y(ui_Panel4, -53);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Panel4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_secondary);
    ui_object_set_themeable_style_property(ui_Panel4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_secondary);
    ui_object_set_themeable_style_property(ui_Panel4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_button2);
    ui_object_set_themeable_style_property(ui_Panel4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_button2);

    ui_Panel1 = lv_obj_create(ui_home_screen);
    lv_obj_set_width(ui_Panel1, 33);
    lv_obj_set_height(ui_Panel1, 14);
    lv_obj_set_x(ui_Panel1, 134);
    lv_obj_set_y(ui_Panel1, -70);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xC51410), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_home_screen);
    lv_obj_set_width(ui_Panel2, 33);
    lv_obj_set_height(ui_Panel2, 14);
    lv_obj_set_x(ui_Panel2, 134);
    lv_obj_set_y(ui_Panel2, -53);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x005DBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_home_screen);
    lv_obj_set_width(ui_Panel3, 33);
    lv_obj_set_height(ui_Panel3, 14);
    lv_obj_set_x(ui_Panel3, 134);
    lv_obj_set_y(ui_Panel3, -36);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x006B41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_home_screen);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 170);
    lv_obj_set_y(ui_Label1, -53);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "LUX");
    ui_object_set_themeable_style_property(ui_Label1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_button2);
    ui_object_set_themeable_style_property(ui_Label1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_button2);
    lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_home_screen);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 190);
    lv_obj_set_y(ui_Label2, -70);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Air Temp");
    ui_object_set_themeable_style_property(ui_Label2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_button2);
    ui_object_set_themeable_style_property(ui_Label2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_button2);
    lv_obj_set_style_text_align(ui_Label2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_home_screen);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 191);
    lv_obj_set_y(ui_Label3, -36);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Humidity");
    ui_object_set_themeable_style_property(ui_Label3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_button2);
    ui_object_set_themeable_style_property(ui_Label3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_button2);
    lv_obj_set_style_text_align(ui_Label3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_home_screen);
    lv_obj_set_width(ui_Panel5, 85);
    lv_obj_set_height(ui_Panel5, 58);
    lv_obj_set_x(ui_Panel5, -171);
    lv_obj_set_y(ui_Panel5, 41);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Panel5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_secondary);
    ui_object_set_themeable_style_property(ui_Panel5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_secondary);
    ui_object_set_themeable_style_property(ui_Panel5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_button2);
    ui_object_set_themeable_style_property(ui_Panel5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_button2);

    ui_Panel6 = lv_obj_create(ui_home_screen);
    lv_obj_set_width(ui_Panel6, 85);
    lv_obj_set_height(ui_Panel6, 58);
    lv_obj_set_x(ui_Panel6, -171);
    lv_obj_set_y(ui_Panel6, 103);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Panel6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_secondary);
    ui_object_set_themeable_style_property(ui_Panel6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_secondary);
    ui_object_set_themeable_style_property(ui_Panel6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_button2);
    ui_object_set_themeable_style_property(ui_Panel6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_button2);

    ui_Panel7 = lv_obj_create(ui_home_screen);
    lv_obj_set_width(ui_Panel7, 85);
    lv_obj_set_height(ui_Panel7, 58);
    lv_obj_set_x(ui_Panel7, -76);
    lv_obj_set_y(ui_Panel7, 103);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Panel7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_secondary);
    ui_object_set_themeable_style_property(ui_Panel7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_secondary);
    ui_object_set_themeable_style_property(ui_Panel7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_button2);
    ui_object_set_themeable_style_property(ui_Panel7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_button2);

    ui_Panel9 = lv_obj_create(ui_home_screen);
    lv_obj_set_width(ui_Panel9, 85);
    lv_obj_set_height(ui_Panel9, 58);
    lv_obj_set_x(ui_Panel9, -76);
    lv_obj_set_y(ui_Panel9, 41);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Panel9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_secondary);
    ui_object_set_themeable_style_property(ui_Panel9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_secondary);
    ui_object_set_themeable_style_property(ui_Panel9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_button2);
    ui_object_set_themeable_style_property(ui_Panel9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_button2);

    ui_Panel8 = lv_obj_create(ui_home_screen);
    lv_obj_set_width(ui_Panel8, 85);
    lv_obj_set_height(ui_Panel8, 58);
    lv_obj_set_x(ui_Panel8, 19);
    lv_obj_set_y(ui_Panel8, 41);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Panel8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_secondary);
    ui_object_set_themeable_style_property(ui_Panel8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_secondary);
    ui_object_set_themeable_style_property(ui_Panel8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_button2);
    ui_object_set_themeable_style_property(ui_Panel8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_button2);

    ui_Panel10 = lv_obj_create(ui_home_screen);
    lv_obj_set_width(ui_Panel10, 85);
    lv_obj_set_height(ui_Panel10, 58);
    lv_obj_set_x(ui_Panel10, 19);
    lv_obj_set_y(ui_Panel10, 103);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Panel10, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_secondary);
    ui_object_set_themeable_style_property(ui_Panel10, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_secondary);
    ui_object_set_themeable_style_property(ui_Panel10, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_button2);
    ui_object_set_themeable_style_property(ui_Panel10, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_button2);

    uic_Roller1 = ui_Roller1;
    uic_Image3 = ui_Image3;
    uic_Chart1 = ui_Chart1;
    uic_Panel4 = ui_Panel4;
    uic_Label1 = ui_Label1;
    uic_Label3 = ui_Label3;

}

void ui_home_screen_screen_destroy(void)
{
    if(ui_home_screen) lv_obj_del(ui_home_screen);

    // NULL screen variables
    ui_home_screen = NULL;
    uic_Roller1 = NULL;
    ui_Roller1 = NULL;
    uic_Image3 = NULL;
    ui_Image3 = NULL;
    uic_Chart1 = NULL;
    ui_Chart1 = NULL;
    uic_Panel4 = NULL;
    ui_Panel4 = NULL;
    ui_Panel1 = NULL;
    ui_Panel2 = NULL;
    ui_Panel3 = NULL;
    uic_Label1 = NULL;
    ui_Label1 = NULL;
    ui_Label2 = NULL;
    uic_Label3 = NULL;
    ui_Label3 = NULL;
    ui_Panel5 = NULL;
    ui_Panel6 = NULL;
    ui_Panel7 = NULL;
    ui_Panel9 = NULL;
    ui_Panel8 = NULL;
    ui_Panel10 = NULL;

}
