// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_OPENING_SCREEN_H
#define UI_OPENING_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_opening_screen
extern void ui_opening_screen_screen_init(void);
extern void ui_opening_screen_screen_destroy(void);
extern void ui_event_opening_screen(lv_event_t * e);
extern lv_obj_t * ui_opening_screen;
extern lv_obj_t * ui_Image1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_opening_screen;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

