// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_opening_screen;
lv_obj_t * ui_opening_screen = NULL;
lv_obj_t * ui_Image1 = NULL;
// event funtions
void ui_event_opening_screen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        devicestart_Animation(ui_Image1, 500);
        _ui_screen_change(&ui_home_screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 4500, &ui_home_screen_screen_init);
    }
}

// build funtions

void ui_opening_screen_screen_init(void)
{
    ui_opening_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_opening_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_opening_screen);
    lv_img_set_src(ui_Image1, &ui_img_1255442560);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 480
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 270
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_opening_screen, ui_event_opening_screen, LV_EVENT_ALL, NULL);
    uic_opening_screen = ui_opening_screen;

}

void ui_opening_screen_screen_destroy(void)
{
    if(ui_opening_screen) lv_obj_del(ui_opening_screen);

    // NULL screen variables
    uic_opening_screen = NULL;
    ui_opening_screen = NULL;
    ui_Image1 = NULL;

}
