// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_background[3] = {0x050E3C, 0x000000, 0xFAF3E1};
const ui_theme_variable_t _ui_theme_alpha_background[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_secondary[3] = {0x002455, 0x232D3F, 0xF5E7C6};
const ui_theme_variable_t _ui_theme_alpha_secondary[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_button[3] = {0xDC0000, 0x005B41, 0xFF6D1F};
const ui_theme_variable_t _ui_theme_alpha_button[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_tersier[3] = {0xFF6D1F, 0x092635, 0x222222};
const ui_theme_variable_t _ui_theme_alpha_tersier[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_button2[3] = {0xFF3838, 0x008170, 0x002455};
const ui_theme_variable_t _ui_theme_alpha_button2[3] = {255, 255, 255};
uint8_t ui_theme_idx = UI_THEME_DARK_MODE;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

